Adding AWS server setup scripts
aniket03/SR_proj pull request #1
Opened 2017-02-09 08:11 UTC by aniket03

Adding file to setup Server on EC2
Adding file to cluster nodes and set HA policy

2017-02-09 08:39 UTC, ketanbhatt requested changes
Good work

2017-02-09 08:39 UTC, ketanbhatt commented on set_RMQ_EC2.py
> +##Should run on local machine
Refer to https://www.python.org/dev/peps/pep-0008
Comments should start with one `#`

2017-02-09 08:39 UTC, ketanbhatt commented on set_RMQ_EC2.py
> +	'ec2-54-173-2-90.compute-1.amazonaws.com'		##Your instance's public name
Inline comments should be separated by two spaces. 
```py
a = b  # dummy comment
```

2017-02-09 08:39 UTC, ketanbhatt commented on set_RMQ_EC2.py
> +k = paramiko.RSAKey.from_private_key_file("/home/aniket/Downloads/rabbitmqkey.pem")
`k` doesnt tell me what it is. So variable names should be readable.

2017-02-09 08:39 UTC, ketanbhatt commented on set_RMQ_EC2.py
> +k = paramiko.RSAKey.from_private_key_file("/home/aniket/Downloads/rabbitmqkey.pem")
`"/home/aniket/Downloads/rabbitmqkey.pem"`
things like these can be set as variables and then variables can be used in the code later. 

So later if I want to change the values of these params, I dont have to read the full code, just change the value of the params

2017-02-09 08:39 UTC, ketanbhatt commented on set_RMQ_EC2.py
> +	ssh = paramiko.SSHClient()
`ssh_client`

2017-02-09 08:39 UTC, ketanbhatt commented on set_RMQ_EC2.py
> +	## To execute the commands
This comment is not needed

2017-02-09 08:39 UTC, ketanbhatt commented on set_RMQ_EC2.py
> +	commands =[
`commands_to_be_executed`

2017-02-09 08:39 UTC, ketanbhatt commented on set_RMQ_EC2.py
> +		'sudo -i apt-get install rabbitmq-server -y',
Maybe add inline comments telling what each command is doing.

2017-02-09 08:39 UTC, ketanbhatt commented on set_RMQ_EC2.py
> +	single_command = ""
Making a list and changing that to string is faster than appending to strings.

2017-02-09 08:39 UTC, ketanbhatt commented on set_RMQ_EC2.py
> +	single_command = ""
Also, based on the usage, you could just do `single_command = '\n'.join(commands)`

2017-02-09 08:39 UTC, ketanbhatt commented on set_RMQ_EC2.py
> +	single_command = ""
`single_command` --> `command_to_execute`

2017-02-09 08:39 UTC, ketanbhatt commented on set_RMQ_EC2.py
> +Chain of Events
Move this to some other file if you want.

2017-02-09 08:39 UTC, ketanbhatt commented on set_RMQ_EC2.py
> +Chain of Events
Also: There are no multiline comments in python yet.
https://www.python.org/dev/peps/pep-0008/#block-comments

Also, fun: https://twitter.com/vinayakcoder/status/670178989500071937

2017-02-09 08:39 UTC, ketanbhatt commented on set_RMQ_EC2.py
> +		'sudo -i rabbitmqctl cluster_status',
This is not required.

2017-02-09 08:39 UTC, ketanbhatt commented on set_RMQ_cluster_AMI.py
> +hostnames = [
This can be made using master and slaves.

2017-02-09 08:39 UTC, ketanbhatt commented on set_RMQ_cluster_AMI.py
> +]	##Since there can be multiple slaves
Comment not required

2017-02-09 08:39 UTC, ketanbhatt commented on set_RMQ_cluster_AMI.py
> +pr_ip = {}	## Dict to store private ip of each host
Better naming required

2017-02-09 08:39 UTC, ketanbhatt commented on set_RMQ_cluster_AMI.py
> +	session.exec_command("hostname")
Can I directly read the output of this command? There has to be a way

2017-02-09 08:39 UTC, ketanbhatt commented on set_RMQ_cluster_AMI.py
> +	stdin = session.makefile('wb', -1)
Files not required too.

2017-02-09 08:39 UTC, ketanbhatt commented on set_RMQ_EC2.py
> +	stdin = session.makefile('wb', -1)
Not required

2017-02-09 08:39 UTC, ketanbhatt commented on set_RMQ_cluster_AMI.py
> +	ssh = paramiko.SSHClient()
Since setting up is same, lets abstract this to a method

2017-02-09 08:39 UTC, ketanbhatt commented on set_RMQ_cluster_AMI.py
> +session.exec_command("sudo rabbitmqctl set_policy ha-all \"\" \'{\"ha-mode\":\"all\",\"ha-sync-mode\":\"automatic\"}\'")
This command is not readable. 
Lets define the policy in a dict and then do a json.dumps() to get a string for it.

2017-02-12 10:49 UTC, aniket03 reviewed
Fine

2017-02-12 10:50 UTC, merged

2017-02-12 18:10 UTC, ketanbhatt commented
@aniket03 so we generally do the review until the reviewer says that further review is not required. 

Please take care next time 😄